title: Seminar Docs
theme: just-the-docs
color_scheme: light
logo: # optional: /assets/logo.png
url: https://deyksanjeeb.github.io

# Enable built-in search
search_enabled: true

# Navigation (order + titles)
nav_order: 1
nav_external_links:
  - title: GitHub
    url: https://github.com/deyksanjeeb

# Sidebar structure (optional explicit ordering)
just_the_docs:
  collections:
    docs:
      name: Docs
      nav_fold: true
      nav_exclude: false
